version: '3.8'
services:
  sharedconfigsapp:
    build:
      context: ./sharedConfigs
    ports:
      - "8084:8080"
#    networks:
#      - mynetwork

  calculatorapp:
    build:
      context: ./calculator
    ports:
      - "8080:8080"
#    networks:
#      - mynetwork

  statementapp:
    build:
      context: ./statement
    ports:
      - "8082:8080"
#    networks:
#      - mynetwork

  dealapp:
      build:
        context: ./deal
      ports:
        - "8081:8080"
#      networks:
#        - mynetwork

  dossierapp:
        build:
          context: ./dossier
        ports:
          - "8083:8080"
#        networks:
#          - mynetwork

  gatewayapp:
        build:
          context: ./gateway
        ports:
          - "8000:8080"
#        networks:
#          - mynetwork

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER= ${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=dbCreditBank
    ports:
      - "54322:5432"
    volumes:
      - /d/IdeaProjects/MVP2/pgdata:/var/lib/postgresql/data
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1   # уникальный идентификатор (ID) для брокера Kafka.
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  # указывает, как Kafka должен подключаться к Zookeeper
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092,OUTSIDE://localhost:9093 # определяет, как другие клиенты и брокеры должны подключаться к этому брокеру. В данном случае, брокер будет объявлять, что он доступен по адресу на порту 9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT # задает карту протоколов безопасности для слушателей. В данном случае, она указывает, что для протокола PLAINTEXT используется также протокол PLAINTEXT. Это означает, что соединения не будут защищены.
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE #  указывает, какой слушатель (listener) будет использоваться для связи между брокерами в кластере. В данном случае, для межброкерских соединений будет использоваться слушатель с именем PLAINTEXT
      KAFKA_CREATE_TOPICS: "finish-registration:1:1,create-documents:1:1,send-documents:1:1,send-ses:1:1,credit-issued:1:1,statement-denied:1:1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper