spring.application.name=gateway
# Swagger (Springdoc)
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
server.port=8000
spring.datasource.url=jdbc:postgresql://postgres:5432/dbCreditBank
#spring.datasource.username=${POSTGRES_USER}
#spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.username=usr1
spring.datasource.password=usrpswd